package com.dzd.phonebook.util.send.api.qwsend;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SenderService service = new SenderService();
 * SenderDelegate portType = service.getSenderPort();
 * portType.send(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SenderService", targetNamespace = "http://impl.ws.zyz.com/", wsdlLocation = "http://qf.sms3.cn/SenderPort?wsdl")
public class SenderService extends Service {

	private final static URL SENDERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(SenderService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = SenderService.class.getResource(".");
			url = new URL(baseUrl, "http://qf.sms3.cn/SenderPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://qf.sms3.cn/SenderPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDERSERVICE_WSDL_LOCATION = url;
	}

	public SenderService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SenderService() {
		super(SENDERSERVICE_WSDL_LOCATION, new QName("http://impl.ws.zyz.com/","SenderService"));
	}

	/**
	 * 
	 * @return returns SenderDelegate
	 */
	@WebEndpoint(name = "SenderPort")
	public ISendWs getSenderPort() {
		return super.getPort(new QName("http://impl.ws.zyz.com/", "SenderPort"),ISendWs.class);
	}

}
